---
title: "IUCN decline species"
author: "CGRC Staff - Scott Jennings"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE)
```


```{r}


library(tidyverse)
library(here)
library(birdnames)
library(flextable)
custom_bird_list <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/my_R_general/birdnames_support/data/custom_bird_list") 

source(here("code/analysis_utilities.R"))


iucn <- readRDS(here("data_files/all_best_preds_response")) %>% 
  mutate(common.name = ifelse(alpha.code == "ALL", "All species combined", translate_bird_names(alpha.code, "alpha.code", "common.name"))) %>% 
  group_by(common.name, Modnames) %>% 
  is_iucn_threatened_trend() %>% 
  mutate(which.year = case_when(study.year == min(study.year) ~ "first",
                                study.year == max(study.year) ~ "last")) %>% 
  ungroup() %>% 
  filter(!is.na(which.year)) %>% 
  select(common.name, Modnames, decline.dur, study.year, which.year) %>% 
  pivot_wider(id_cols = c(common.name, Modnames, decline.dur), names_from = which.year, values_from = study.year) %>% 
  mutate(first = as.character(first),
         last = as.character(last))

```



```{r}
flextable(iucn) %>%
  add_header_row(values = c("", "", "Decline\nmeeting IUCN criteria"), colwidths = c(1, 1, 3))%>% 
  set_header_labels(common.name = "Species",
                    Modnames = "Model",
                    decline.dur = "Total years",
                    first = "Start",
                    last = "End") %>% 
  align(j = 3:5, align = "center", part = "all") %>%  
  autofit()
  
```


