---
title: "All species detected"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```




```{r}

library(tidyverse)
library(here)
library(birdnames)
library(flextable)
library(ftExtra)
library(officer)


source(here("code/analysis_utilities.R"))


custom_bird_list <- readRDS("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/my_R_general/birdnames_support/data/custom_bird_list")



```


```{r}




spp_day_total <- readRDS(here("data_files/spp_day_total_ungrouped"))

spp_min_max <- spp_day_total %>% 
  group_by(alpha.code) %>% 
  mutate(min.max = case_when(bay.total == max(bay.total) ~ "zmax",
                             bay.total == min(bay.total) ~ "zmin",
                             TRUE ~ NA)) %>%
  ungroup() %>% 
  distinct(alpha.code, bay.total, min.max) %>% 
  filter(!is.na(min.max)) %>% 
  pivot_wider(id_cols = alpha.code, values_from = bay.total, names_from = min.max) %>% 
  mutate(zmin = replace_na(zmin, 0)) %>% 
  pivot_longer(cols = c(zmin, zmax), values_to = "bay.total", names_to = "min.max") %>% 
  arrange(alpha.code, bay.total)%>% 
  pivot_wider(id_cols = alpha.code, values_from = bay.total, names_from = min.max)

spp_n_years <- spp_day_total %>% 
  distinct(alpha.code, study.year) %>% 
  group_by(alpha.code) %>% 
  summarise(n.years = n()) %>% 
  ungroup()

ibp <- read.csv("C:/Users/scott.jennings/OneDrive - Audubon Canyon Ranch/Projects/my_R_general/birdnames_support/data/IBP-AOS-LIST23.csv") 

all_spec_levs <- ibp %>% 
  select("alpha.code" = SPEC) %>% 
  mutate(alpha.code = factor(alpha.code),
         alpha.code = fct_inorder(alpha.code))

wbird_spec_levs <- spp_n_years %>% 
  select(alpha.code) %>% 
  mutate(alpha.code = factor(alpha.code),
         alpha.code = fct_inorder(alpha.code))

z_spec_levs <- bind_rows(all_spec_levs, wbird_spec_levs) %>% 
  distinct()


spp_detected <- full_join(spp_min_max, spp_n_years) %>% 
  mutate(common.name = translate_bird_names(alpha.code, "alpha.code", "common.name"),
         sci.name = translate_bird_names(alpha.code, "alpha.code", "species")) %>%
  mutate(alpha.code = factor(alpha.code, levels = z_spec_levs$alpha.code),
         alpha.code = fct_drop(alpha.code),
         alpha.code = fct_relevel(alpha.code, "CORM", after = match("DCCO", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "GOLDENEYES", after = match("BAGO", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "GOOSE", after = match("CANG", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "HEGR", after = match("EAGR", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "LOON", after = match("YBLO", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "MERG", after = match("RBME", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "MURRELET", after = match("RHAU", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "PCLO", after = match("YBLO", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "SCAUP", after = match("LESC", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "SCOTER", after = match("BLSC", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "TUDUSCAUP", after = match("SCAUP", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "DUCK", after = match("RUDU", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "SWAN", after = match("MUSW", levels(alpha.code))),
         alpha.code = fct_relevel(alpha.code, "WCGR", after = Inf),
         alpha.code = fct_relevel(alpha.code, "WCGR", after = match("CLGR", levels(alpha.code)))) %>% 
  mutate(common.name = gsub("spp", "spp.", common.name),
         common.name = ifelse(common.name == "Unidentified Duck", "Duck spp.", common.name),
         common.name = ifelse(common.name == "Cormorant", "Cormorant spp.", common.name)) %>% 
  arrange(alpha.code)



```

Supplementary table 1. All taxa detected during waterbird surveys at Tomales Bay, California, 1992-2022. Shown for each taxa are the number of years the species was detected on at least one survey, and the minimum and maximum number counted on any single survey.

```{r}
flextable(spp_detected, col_keys = c("dummy", "n.years", "zmin", "zmax")) %>% 
  compose(j = "dummy", value = as_paragraph(common.name, " (", as_i(sci.name), ")")) %>% 
  add_header_row(values = c("", "", "Single day count"), colwidths = c(1, 1, 2)) %>%
  set_header_labels(out.name = "Species",
                    n.years = "# years detected",
                    zmin = "Minimum",
                    zmax = "Maximum")%>% 
  align(j = 2:4, align = "center", part = "all") %>%  
  border_remove() %>% 
  border(i = 2, j = 3:4, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 2, border.bottom = fp_border(color = "black"), part = "header") %>%
  border(i = nrow(spp_detected), border.bottom = fp_border(color = "black"), part = "body") %>%
  autofit() %>% 
  fit_to_width(max_width = 7.5)
```


